import { Inter } from "next/font/google";
import "./globals.css";
import FormContextProvider from "@/context/FromContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Details Connection",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <FormContextProvider>
        <body className={inter.className}>{children}</body>
      </FormContextProvider>
    </html>
  );
}
